name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # mainブランチへのpush時にデプロイ
  workflow_dispatch:  # 手動実行も可能

env:
  AZURE_WEBAPP_NAME: app-002-gen10-step3-1-py-oshima38  # ← ここを変更してください
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          # 必要なファイルの存在確認
          echo "Checking required files..."
          ls -la startup.sh gunicorn.conf.py app.py
          
          # デプロイパッケージを作成
          echo "Creating deployment package..."
          zip -r deploy.zip . \
            -x '*.git*' \
            -x '*venv*' \
            -x '*.env*' \
            -x '*__pycache__*' \
            -x '*.github*' \
            -x '*.pytest_cache*' \
            -x '*.coverage*'
          
          # パッケージ内容の確認
          echo "Package contents:"
          unzip -l deploy.zip | head -20

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          echo "Unzipping deployment package..."
          unzip deploy.zip
          echo "Deployment files extracted:"
          ls -la

      - name: Verify deployment files
        run: |
          echo "Verifying critical files..."
          test -f app.py && echo "✓ app.py found" || echo "✗ app.py missing"
          test -f startup.sh && echo "✓ startup.sh found" || echo "✗ startup.sh missing"
          test -f gunicorn.conf.py && echo "✓ gunicorn.conf.py found" || echo "✗ gunicorn.conf.py missing"
          test -f requirements.txt && echo "✓ requirements.txt found" || echo "✗ requirements.txt missing"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
